# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# http://voidmainvoid.tistory.com/40

spring:
  profiles:
    active:
    - local
  aop:
    auto: true
    proxy-target-class: true
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  devtools:
    livereload:
      enabled: true  
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /console
      
#server:
#  context-path: /test 
      
#----------------------------------
# BootLoginApplication.java 참고
#----------------------------------
#flyway:
#  baseline-on-migrate: true
#  enabled: true 
#mybatis:
#  config-location: classpath:mybatis/configuration.xml
#  mapper-locations:
#  - classpath:mybatis/mappers/account/**/*.xml

---
spring:
  profiles: local
datasource:
  account:
    driver-class-name: org.h2.Driver
    url : jdbc:h2:D:\accountdb
    username: sa
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 30000
      connection-test-query: select 1 from dual
      
---
spring:
  profiles: dev
datasource:
  account:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy 
    url : jdbc:log4jdbc:h2:mem:accountdb
    username: sa
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-test-query: select 1 from dual
      
---
spring:
  profiles: prod
datasource:
  account:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy 
    url : jdbc:log4jdbc:h2:mem:accountdb
    username: sa
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-test-query: select 1 from dual